dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=main/ -m unittest discover tests

after_success:
  - coveralls
